-- Tabela: Patios (do @Entity Patios)
CREATE TABLE IF NOT EXISTS Patios (
  id_patio BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome     VARCHAR(100) NOT NULL,
  telefone VARCHAR(20),
  endereco VARCHAR(200)
);