-- Tabela: Pontos_Leitura (do @Entity PontosLeitura)
CREATE TABLE IF NOT EXISTS Pontos_Leitura (
  id_ponto   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_patio   BIGINT NOT NULL,
  nome_ponto VARCHAR(50) NOT NULL,
  descricao  VARCHAR(200),

  CONSTRAINT fk_ponto_patio
    FOREIGN KEY (id_patio) REFERENCES Patios(id_patio)
    ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_pontos_patio ON Pontos_Leitura (id_patio);
CREATE INDEX IF NOT EXISTS idx_pontos_nome  ON Pontos_Leitura (nome_ponto);
