-- Tabela: Movimentacoes (do @Entity Movimentacoes)
CREATE TABLE IF NOT EXISTS Movimentacoes (
  id_movimentacao BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_moto         VARCHAR(50),
  id_ponto        BIGINT,
  data_hora       TIMESTAMP,

  CONSTRAINT fk_mov_moto
    FOREIGN KEY (id_moto) REFERENCES Motos(id_moto)
    -- Sem ON DELETE CASCADE por padrão (o @ManyToOne não marca como nullable=false).
    -- Se quiser bloquear exclusão de Motos com movimentação, deixe sem ação (padrão).
    ,

  CONSTRAINT fk_mov_ponto
    FOREIGN KEY (id_ponto) REFERENCES Pontos_Leitura(id_ponto)
    ON DELETE CASCADE
);